### ISSUE TITLE
西北工业大学 链接不能打开

### ISSUE THREAD

**Issue by DGGua** [CS-BAOYAN/CSYuTuiMian2022#15]
而且网站搜索没有找到预推免相关通知

**Comment by Sumsky21** [comment]
我这里可以打开呀，Win11/Edge浏览器，换个设备或者网络环境试试呢

![image](https://user-images.githubusercontent.com/58537872/190105802-cdf6439b-8e8d-4518-8d43-69a74b60e017.png)

**Comment by DGGua** [comment]
可以打开了，之前不知道为什么报404问题
