### ISSUE TITLE
buaa cs 的截至时间应该是9.21 18:00?

### ISSUE THREAD

**Issue by only-tao** [CS-BAOYAN/CSYuTuiMian2022#22]
rt, 
![image](https://user-images.githubusercontent.com/54075362/190904543-3e8e222e-ceb7-49ef-82fa-10fc6afdc14f.png)

**Comment by Sumsky21** [comment]
请问你这是在哪里看到的？我在官网上查到的文件上还是20号

<img width="444" alt="image" src="https://user-images.githubusercontent.com/58537872/190912352-6bacfd2e-f6a5-4f61-af1a-a458829ed0dc.png">

**Comment by only-tao** [comment]
不好意思,我之前下载用来参考的文件是去年的,去年的是9.21
